version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file: .env-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  server:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./deployment/Dockerfile
    depends_on:
      - postgres
    ports:
      - 5000:5000
    env_file: ./deployment/.env
    restart: always

volumes:
  postgres_db:
